name: flutter_stories_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_stories:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
